// node-server/.frontend/src/views/Login.vue
<template>
  <default-drawer
  >
    <template
      v-slot:main
    >
      <Login />
    </template>
  </default-drawer>
</template>

<script>
  export default {
    components: {
       DefaultDrawer: () => import(
        '../components/Drawer.vue'
      ),
       Login: () => import(
        '../components/Login.vue'
      ),
    },
  }
</script>

// react-app/src/views/users/Login.js
import React, { useState, useEffect, useRef, useContext } from 'react';
import Drawer from '../../components/Drawer.js';
import Login from '../../components/users/Login.js';

const LoginView = () => {
    return (    
        <div>
            <Drawer>
                {/* All components */}
                <Login />
            </Drawer>
        </div>
    )
}


export default LoginView;
