// node-server/.frontend/src/views/Register.vue
<template>
  <default-drawer>
    <template
      v-slot:main
    >
      <Register />
    </template>
  </default-drawer>
</template>

<script>
  // import Register from '../components/Register'
  export default {

    components: {
       DefaultDrawer: () => import(
        '../components/Drawer.vue'
      ),
       Register: () => import(
        '../components/Register.vue'
      ),
    },
  }
</script>

// react-app/src/views/users/Register.js
import React, { useState, useEffect, useRef, useContext } from 'react';
import Drawer from '../../components/Drawer.js';
import Register from '../../components/users/Register.js';

const RegisterView = () => {
    return (    
        <div>
            <Drawer>
                {/* All components */}
                <Register />
            </Drawer>
        </div>
    )
}


export default RegisterView;
